### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by masaddy** [walangkaji/zte-f670-api#1]
Gan kok selalu 404 Not Found terus y hasil response nya, salah dimana nya y

**Comment by walangkaji** [comment]
coba screenshoot hasilnya pak, pengen lihat errornya gimana, di saya masih jalan kok,

![Screenshot_1](https://user-images.githubusercontent.com/12222084/108074903-4cc32a80-709c-11eb-9625-25e6ffe03538.png)

**Comment by masaddy** [comment]
![zte1](https://user-images.githubusercontent.com/12092927/108139852-870be680-70f3-11eb-935d-481285c7b99d.png)

**Comment by masaddy** [comment]
saya debug pas cek login  ...
hasil return dari request nya selalu Not Found ... padahal kalau saya coba login langsung bisa masuk ...

**Comment by walangkaji** [comment]
`404 Not Found` emang keluar kalau belum login pak, cookienya belum di create sebelum submit login,
dicoba dulu `login` tanpa di `exit` di fungsi cekLogin.

kita asumsikan kalo pagenya masih 404 itu brarti belum login, kalo sudah normal 200 itu brarti kita dianggap sudah login.
